### ISSUE TITLE
404 Error when visiting www.fronvo.com/app directly

### ISSUE THREAD

**Issue by ziwenwang1994** [Fronvo/fronvo-site#18]
It seems like an issue with the file path referenced by the site. Should look into it.

![image](https://github.com/Fronvo/site/assets/125798479/3f059d1b-4c93-4256-a097-9abf5a9ee808)

**Comment by StamTsag** [comment]
I'm currently working on a complete rewrite of Fronvo with React and shadcn so it will be resolved.

Thanks for the issue though!
